### ISSUE TITLE
PC to Switch conversion bug

### ISSUE THREAD

**Issue by iSharingan** [Andoryuuta/MHS2SaveKeygen#1]
There is currently a small issue with converting saves from PC to Switch. Currently the bytes 0x00-0x2F are deleted on the assumption that they are all part of the Switch file header, but this is not the case. Some of the bytes are needed on a much smaller Switch header (the PC header is actually 0x40 and Switch header is 0x10)

The solution is to delete bytes 0xC-0x3B instead of 0x00-0x2F. This is in effect the same as adding 0x18 at byte 8 after deleting 0x00-0x2F (It seems the 0x01 at byte 0x00 occasionally causes an issue - in which case setting it to 0x00 fixes it). if the 0x18 is NOT present on a Switch save at 0x08 or if there's data in bytes 0xC-0xF, the game won't load it on Switch. Deleting 0xC-0x3B is to future-proof the method in case updates change something in the header. The 8 bytes removed from the end of the file remains the same in all cases.

Screen shots included as an example/to provide detail:
![image](https://user-images.githubusercontent.com/3332462/125524085-4013a356-ff79-4fba-9cfa-08b804040ef4.png)

Note that this does NOT correct save deletion due to missing DLC files. Only buying/DLing the DLC on the other platform too will fix that. Kamuna Garb (Ena) and Kamuna Armor (Player) both don't count as DLC.

[Resolution process can be found here.](https://github.com/AsteriskAmpersand/MHST2-Save-Tools/issues/2)

Edit: never mind. save conversion only appears to be a feature of the spinoff tool in the link above. I'll leave the text here for anyone else who shows up here and needs it to manually convert a decrypted PC save for Switch.

**Comment by Jfowler30** [comment]
how do i edit the save to delete the header or whatever this means lol im on 1.5.0 and my save wont show so i assume i have to delete something somehow??

**Comment by iSharingan** [comment]
Follow the link in my previous comment for a tool to automatically convert your save - though if you bought any of the DLC for one version of the game that isnt present on the other version, your save will never work untill the coresponding DLC is re-purchased on the other platform.
